### PR TITLE
Add --save-dev to README for npm install command

### PR DESCRIPTION
**Pull request by JanCizmar**

### CODE REVIEW

**Comment by saikatdas0790** [comment]
@JanCizmar I don't think this adds any value at all. Going to close this. Let me know if I'm missing something and I'll reopen

**Comment by JanCizmar** [comment]
When you are installing package like this, you want it to be saved in devDependencies of your package.json. Every user will need to add this manually.

**Comment by saikatdas0790** [comment]
@JanCizmar I believe it won't matter, because when your project gets built, your bundler will simply use this to replace all the environment variable instances with their values and the code from this package won't be included in your deployed web app at all. Is there an instance when you foresee the package source code being included in your bundle?

**Comment by JanCizmar** [comment]
You're right. I didn't know that npm changed the behaviour of `npm install` without param. It's now saved to dependencies by default. Sorry then.

**Pull request closed without merging**
